# recetas_mejoradas.py
# Base de datos MEJORADA con CENAS RENOVADAS tipo desayuno

RECETARIO = {
    # ==========================================================
    # 25 DESAYUNOS (Mantienen la esencia original)
    # ==========================================================
    "Desayunos": [
        {"nombre": "Arepa Reina Pepiada Power", "macros": {"cal": 650, "prot": 35, "carb": 60, "fat": 28}, "instrucciones": "1. Asar arepa.\n2. Mezclar pollo, palta y yogurt.\n3. Rellenar.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Pechuga de Pollo", "cantidad": 120, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Palta", "cantidad": 50, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Yogurt Griego", "cantidad": 30, "unidad": "g", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Arepa Pelúa", "macros": {"cal": 680, "prot": 40, "carb": 60, "fat": 25}, "instrucciones": "Rellenar con carne mechada y queso rallado.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Carne Mechada", "cantidad": 120, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Queso Amarillo", "cantidad": 40, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Arepa Catira", "macros": {"cal": 660, "prot": 40, "carb": 60, "fat": 24}, "instrucciones": "Pollo desmechado con queso amarillo.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Pechuga de Pollo", "cantidad": 120, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Queso Amarillo", "cantidad": 40, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Arepa Dominó", "macros": {"cal": 620, "prot": 28, "carb": 75, "fat": 18}, "instrucciones": "Caraotas negras y queso blanco.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Caraotas Negras", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Queso Llanero", "cantidad": 50, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Arepa con Perico", "macros": {"cal": 600, "prot": 25, "carb": 60, "fat": 22}, "instrucciones": "Huevos revueltos con tomate y cebolla.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Huevos", "cantidad": 3, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Tomate y Cebolla", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Arepa Viuda con Atún", "macros": {"cal": 580, "prot": 35, "carb": 60, "fat": 15}, "instrucciones": "Rellenar con ensalada de atún.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Atún en Agua", "cantidad": 120, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Vegetales", "cantidad": 50, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Arepa de Chía y Avena", "macros": {"cal": 610, "prot": 25, "carb": 70, "fat": 18}, "instrucciones": "Mezclar semillas en la masa.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 60, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Avena", "cantidad": 20, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Chía", "cantidad": 10, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Queso", "cantidad": 50, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Panquecas Bluhealth", "macros": {"cal": 590, "prot": 42, "carb": 75, "fat": 12}, "instrucciones": "Licuar avena, prote, claras y plátano.", "ingredientes": [{"item": "Avena", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Scoop Proteína", "cantidad": 1, "unidad": "und", "pasillo": "💊 Suplementos"}, {"item": "Claras Huevo", "cantidad": 4, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Plátano", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Panquecas de Zanahoria", "macros": {"cal": 550, "prot": 30, "carb": 70, "fat": 12}, "instrucciones": "Añadir zanahoria rallada a la mezcla.", "ingredientes": [{"item": "Avena", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Zanahoria", "cantidad": 50, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Huevo", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Panquecas de Espinaca", "macros": {"cal": 540, "prot": 32, "carb": 68, "fat": 14}, "instrucciones": "Licuar con espinaca (no da sabor, solo color y fibra).", "ingredientes": [{"item": "Avena", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Espinaca", "cantidad": 50, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Claras Huevo", "cantidad": 5, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Cachapas de Avena", "macros": {"cal": 580, "prot": 28, "carb": 80, "fat": 18}, "instrucciones": "Licuar maíz dulce con avena y huevo.", "ingredientes": [{"item": "Maíz Dulce", "cantidad": 150, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Avena", "cantidad": 40, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Huevo", "cantidad": 1, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Queso", "cantidad": 50, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Tostadas Francesas Fit", "macros": {"cal": 520, "prot": 30, "carb": 65, "fat": 12}, "instrucciones": "Remojar pan en huevo y leche, dorar.", "ingredientes": [{"item": "Pan Integral", "cantidad": 3, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}, {"item": "Huevo", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Leche Light", "cantidad": 50, "unidad": "ml", "pasillo": "🥛 Lácteos"}, {"item": "Miel", "cantidad": 10, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Avena Trasnochada", "macros": {"cal": 500, "prot": 30, "carb": 65, "fat": 12}, "instrucciones": "Dejar en refri toda la noche.", "ingredientes": [{"item": "Avena", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Leche Light", "cantidad": 150, "unidad": "ml", "pasillo": "🥛 Lácteos"}, {"item": "Scoop Proteína", "cantidad": 1, "unidad": "und", "pasillo": "💊 Suplementos"}]},
        {"nombre": "Sandwich Triple Vital", "macros": {"cal": 600, "prot": 38, "carb": 65, "fat": 20}, "instrucciones": "3 pisos: Pollo/Palta y Huevo/Tomate.", "ingredientes": [{"item": "Pan Multicereal", "cantidad": 3, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}, {"item": "Pechuga de Pollo", "cantidad": 100, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Palta", "cantidad": 40, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Huevo Duro", "cantidad": 1, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Tostadas Salmón", "macros": {"cal": 550, "prot": 30, "carb": 40, "fat": 28}, "instrucciones": "Palta machacada y salmón encima.", "ingredientes": [{"item": "Pan Integral", "cantidad": 2, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}, {"item": "Palta", "cantidad": 60, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Salmón", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Omelette de Pavita", "macros": {"cal": 450, "prot": 45, "carb": 5, "fat": 25}, "instrucciones": "Tortilla rellena de jamón y queso.", "ingredientes": [{"item": "Huevos", "cantidad": 3, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Jamón Pavita", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Queso Fresco", "cantidad": 40, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Huevos Rancheros Fit", "macros": {"cal": 480, "prot": 25, "carb": 30, "fat": 25}, "instrucciones": "Huevos en salsa de tomate y frijoles.", "ingredientes": [{"item": "Huevos", "cantidad": 3, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Tomate", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Frijoles", "cantidad": 50, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Pan Árabe con Perico", "macros": {"cal": 500, "prot": 28, "carb": 50, "fat": 20}, "instrucciones": "Rellenar pan árabe con huevos revueltos.", "ingredientes": [{"item": "Pan Árabe", "cantidad": 2, "unidad": "und", "pasillo": "🍞 Panadería"}, {"item": "Huevos", "cantidad": 3, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Tomate/Cebolla", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Sandwich Atún y Huevo", "macros": {"cal": 520, "prot": 40, "carb": 45, "fat": 18}, "instrucciones": "Mezcla de atún con huevo duro picado.", "ingredientes": [{"item": "Pan Integral", "cantidad": 2, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}, {"item": "Atún", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Huevo Duro", "cantidad": 1, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Revuelto de Champiñones", "macros": {"cal": 420, "prot": 25, "carb": 10, "fat": 28}, "instrucciones": "Saltear hongos y agregar huevos.", "ingredientes": [{"item": "Huevos", "cantidad": 3, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Champiñones", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Espinaca", "cantidad": 50, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Bollitos Pelones", "macros": {"cal": 550, "prot": 25, "carb": 65, "fat": 20}, "instrucciones": "Bolitas de masa hervidas con queso.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Queso Llanero", "cantidad": 50, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Huevo", "cantidad": 1, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Bowl de Yogurt Power", "macros": {"cal": 450, "prot": 30, "carb": 50, "fat": 12}, "instrucciones": "Mezclar yogurt, fruta y granola.", "ingredientes": [{"item": "Yogurt Griego", "cantidad": 250, "unidad": "g", "pasillo": "🥛 Lácteos"}, {"item": "Fruta", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Granola", "cantidad": 30, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Tamalito Verde Fit", "macros": {"cal": 500, "prot": 15, "carb": 60, "fat": 20}, "instrucciones": "Acompañar con salsa criolla y pan.", "ingredientes": [{"item": "Tamal Verde", "cantidad": 1, "unidad": "und", "pasillo": "🥦 Verdulería"}, {"item": "Pan Francés", "cantidad": 1, "unidad": "und", "pasillo": "🍞 Panadería"}]},
        {"nombre": "Salchicha Huachana", "macros": {"cal": 600, "prot": 30, "carb": 40, "fat": 35}, "instrucciones": "Revuelto con huevo (escurrir grasa).", "ingredientes": [{"item": "Salchicha Huachana", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Huevos", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Pan", "cantidad": 2, "unidad": "und", "pasillo": "🍞 Panadería"}]},
        {"nombre": "Batido Hipercalórico", "macros": {"cal": 600, "prot": 40, "carb": 80, "fat": 15}, "instrucciones": "Licuar prote, avena, plátano y maní.", "ingredientes": [{"item": "Scoop Proteína", "cantidad": 1, "unidad": "und", "pasillo": "💊 Suplementos"}, {"item": "Avena", "cantidad": 60, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Plátano", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Mantequilla Maní", "cantidad": 15, "unidad": "g", "pasillo": "🥫 Abarrotes"}]}
    ],

    # ==========================================================
    # 25 ALMUERZOS (Sin cambios, mantienen formato original)
    # ==========================================================
    "Almuerzos": [
        {"nombre": "Pollo Saltado", "macros": {"cal": 820, "prot": 55, "carb": 90, "fat": 20}, "instrucciones": "Wokear pollo y verduras. Servir con papa y arroz.", "ingredientes": [{"item": "Pechuga de Pollo", "cantidad": 200, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Papa Sancochada", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Arroz", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Cebolla/Tomate", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Arroz con Pollo", "macros": {"cal": 850, "prot": 50, "carb": 100, "fat": 22}, "instrucciones": "Guisar pollo en base de culantro con arroz.", "ingredientes": [{"item": "Presa de Pollo", "cantidad": 220, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Arroz", "cantidad": 150, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Culantro", "cantidad": 50, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Ají de Pollo", "macros": {"cal": 750, "prot": 60, "carb": 70, "fat": 22}, "instrucciones": "Crema de ají con pollo deshilachado.", "ingredientes": [{"item": "Pechuga de Pollo", "cantidad": 220, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Papa", "cantidad": 150, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Arroz", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Leche Light", "cantidad": 50, "unidad": "ml", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Estofado de Pollo", "macros": {"cal": 720, "prot": 48, "carb": 80, "fat": 20}, "instrucciones": "Pollo en salsa de tomate con verduras.", "ingredientes": [{"item": "Presa de Pollo", "cantidad": 220, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Papa", "cantidad": 150, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Arroz", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Seco de Pollo", "macros": {"cal": 750, "prot": 50, "carb": 75, "fat": 25}, "instrucciones": "Guiso de culantro con quinua.", "ingredientes": [{"item": "Presa de Pollo", "cantidad": 220, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Quinua Cocida", "cantidad": 200, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Culantro", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Chaufa de Quinua", "macros": {"cal": 700, "prot": 50, "carb": 70, "fat": 20}, "instrucciones": "Salteado estilo chino con quinua.", "ingredientes": [{"item": "Quinua Cocida", "cantidad": 250, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Pechuga de Pollo", "cantidad": 180, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Huevos", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Milanesa al Horno", "macros": {"cal": 650, "prot": 50, "carb": 60, "fat": 18}, "instrucciones": "Empanizar y hornear. Servir con puré.", "ingredientes": [{"item": "Pechuga de Pollo", "cantidad": 180, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Pan Rallado", "cantidad": 30, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Papa (Puré)", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Pabellón Fit", "macros": {"cal": 880, "prot": 55, "carb": 110, "fat": 22}, "instrucciones": "Carne mechada, arroz, caraotas y plátano.", "ingredientes": [{"item": "Carne Mechada", "cantidad": 180, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Arroz", "cantidad": 120, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Caraotas Negras", "cantidad": 150, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Plátano", "cantidad": 120, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Lomo Saltado", "macros": {"cal": 800, "prot": 50, "carb": 85, "fat": 25}, "instrucciones": "Carne salteada con papa frita (airfryer).", "ingredientes": [{"item": "Carne de Res", "cantidad": 200, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Papa", "cantidad": 150, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Arroz", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Guiso Carne Molida", "macros": {"cal": 780, "prot": 45, "carb": 85, "fat": 25}, "instrucciones": "Con papitas en cubos.", "ingredientes": [{"item": "Carne Molida", "cantidad": 200, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Papa", "cantidad": 150, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Arroz", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Seco de Carne", "macros": {"cal": 780, "prot": 50, "carb": 85, "fat": 25}, "instrucciones": "Guiso norteño con frijoles.", "ingredientes": [{"item": "Carne de Res", "cantidad": 200, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Frijoles", "cantidad": 150, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Culantro", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Olluquito con Carne", "macros": {"cal": 600, "prot": 45, "carb": 65, "fat": 15}, "instrucciones": "Olluco en tiras con carne.", "ingredientes": [{"item": "Olluco", "cantidad": 250, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Carne de Res", "cantidad": 180, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Arroz", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Bistec a lo Pobre", "macros": {"cal": 850, "prot": 60, "carb": 80, "fat": 30}, "instrucciones": "Bistec con huevo y plátano (al horno).", "ingredientes": [{"item": "Bistec", "cantidad": 200, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Huevo", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Plátano", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Arroz", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Pastel de Plátano", "macros": {"cal": 780, "prot": 45, "carb": 100, "fat": 22}, "instrucciones": "Capas de plátano y carne al horno.", "ingredientes": [{"item": "Plátano Maduro", "cantidad": 250, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Carne Molida", "cantidad": 180, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Queso", "cantidad": 60, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Lentejas con Chuleta", "macros": {"cal": 800, "prot": 55, "carb": 95, "fat": 20}, "instrucciones": "Guiso de lentejas con chuleta.", "ingredientes": [{"item": "Lentejas", "cantidad": 250, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Chuleta", "cantidad": 150, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Arroz", "cantidad": 120, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Adobo de Cerdo", "macros": {"cal": 750, "prot": 50, "carb": 80, "fat": 25}, "instrucciones": "Cerdo en salsa de ají panca y vinagre.", "ingredientes": [{"item": "Lomo de Cerdo", "cantidad": 200, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Camote", "cantidad": 150, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Ají Panca", "cantidad": 30, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Carapulcra", "macros": {"cal": 800, "prot": 45, "carb": 90, "fat": 28}, "instrucciones": "Papa seca con cerdo.", "ingredientes": [{"item": "Papa Seca", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Cerdo", "cantidad": 180, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Yuca", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Pescado Sudado", "macros": {"cal": 600, "prot": 45, "carb": 60, "fat": 15}, "instrucciones": "Al vapor con cebolla y tomate.", "ingredientes": [{"item": "Filete Pescado", "cantidad": 200, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Arroz", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Yuca", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Atún Saltado", "macros": {"cal": 650, "prot": 40, "carb": 80, "fat": 15}, "instrucciones": "Lata de atún salteada con cebolla/tomate.", "ingredientes": [{"item": "Atún", "cantidad": 180, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Papa", "cantidad": 150, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Arroz", "cantidad": 80, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Salmón con Camote", "macros": {"cal": 700, "prot": 40, "carb": 60, "fat": 30}, "instrucciones": "Horneado con especias.", "ingredientes": [{"item": "Salmón", "cantidad": 180, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Camote", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Espárragos", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Garbanzos con Acelga", "macros": {"cal": 750, "prot": 40, "carb": 90, "fat": 25}, "instrucciones": "Potaje con chorizo.", "ingredientes": [{"item": "Garbanzos", "cantidad": 200, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Acelga", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Chorizo", "cantidad": 50, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Tallarines Verdes", "macros": {"cal": 700, "prot": 30, "carb": 90, "fat": 25}, "instrucciones": "Salsa de espinaca y albahaca.", "ingredientes": [{"item": "Fideos", "cantidad": 150, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Queso Fresco", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Huevo Frito", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Caigua Rellena", "macros": {"cal": 600, "prot": 35, "carb": 60, "fat": 20}, "instrucciones": "Rellena de carne.", "ingredientes": [{"item": "Caigua", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Carne Molida", "cantidad": 150, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Arroz", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Locro de Zapallo", "macros": {"cal": 650, "prot": 30, "carb": 80, "fat": 25}, "instrucciones": "Guiso de zapallo y queso.", "ingredientes": [{"item": "Zapallo Macre", "cantidad": 350, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Queso Fresco", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Arroz", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Pasta Bolognese Pavo", "macros": {"cal": 700, "prot": 45, "carb": 90, "fat": 15}, "instrucciones": "Salsa roja con carne de pavo.", "ingredientes": [{"item": "Fideos", "cantidad": 150, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Carne Molida Pavo", "cantidad": 180, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Salsa Tomate", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}]}
    ],

    # ==========================================================
    # 25 CENAS RENOVADAS - Estilo Desayuno/Ligeras pero Proteicas
    # ==========================================================
    "Cenas": [
        {"nombre": "Arepa Nocturna de Atún", "descripcion": "Ligera pero completa", "macros": {"cal": 520, "prot": 35, "carb": 55, "fat": 15}, "instrucciones": "Asar arepa. Mezclar atún con palta y vegetales. Rellenar.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 70, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Atún en Agua", "cantidad": 120, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Palta", "cantidad": 40, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Arepa Light Queso y Pavo", "descripcion": "Baja en grasa", "macros": {"cal": 480, "prot": 30, "carb": 55, "fat": 12}, "instrucciones": "Arepa rellena de jamón de pavo y queso bajo en grasa.", "ingredientes": [{"item": "Harina P.A.N", "cantidad": 70, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Jamón Pavita", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Queso Light", "cantidad": 40, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Omelette Proteico Cena", "descripcion": "Alto en proteína", "macros": {"cal": 450, "prot": 40, "carb": 8, "fat": 28}, "instrucciones": "Batir huevos. Añadir claras extra. Rellenar con espinaca y queso.", "ingredientes": [{"item": "Huevos", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Claras Huevo", "cantidad": 4, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Espinaca", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Queso", "cantidad": 40, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Panquecas Cena Avena", "descripcion": "Carbos lentos", "macros": {"cal": 500, "prot": 35, "carb": 65, "fat": 10}, "instrucciones": "Licuar avena, claras, proteína. Cocinar. Servir con yogurt.", "ingredientes": [{"item": "Avena", "cantidad": 70, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Claras Huevo", "cantidad": 5, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Scoop Proteína", "cantidad": 0.5, "unidad": "und", "pasillo": "💊 Suplementos"}, {"item": "Yogurt", "cantidad": 50, "unidad": "g", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Sandwich Integral Pollo", "descripcion": "Completo y saciante", "macros": {"cal": 520, "prot": 42, "carb": 55, "fat": 15}, "instrucciones": "Pan integral con pechuga grillada, lechuga y tomate.", "ingredientes": [{"item": "Pan Integral", "cantidad": 2, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}, {"item": "Pechuga de Pollo", "cantidad": 120, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Lechuga/Tomate", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Wrap de Pavo Light", "descripcion": "Bajo en calorías", "macros": {"cal": 450, "prot": 38, "carb": 50, "fat": 10}, "instrucciones": "Tortilla integral con pavo, lechuga y mostaza.", "ingredientes": [{"item": "Tortilla Integral", "cantidad": 2, "unidad": "und", "pasillo": "🍞 Panadería"}, {"item": "Pavo Molido", "cantidad": 120, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Vegetales", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Tostadas Palta Huevo", "descripcion": "Grasas saludables", "macros": {"cal": 480, "prot": 25, "carb": 40, "fat": 25}, "instrucciones": "Pan tostado con palta machacada y huevo poché.", "ingredientes": [{"item": "Pan Integral", "cantidad": 2, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}, {"item": "Palta", "cantidad": 60, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Huevo", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Bowl Yogurt Nocturno", "descripcion": "Digestión fácil", "macros": {"cal": 420, "prot": 32, "carb": 45, "fat": 12}, "instrucciones": "Yogurt griego con frutos rojos y almendras.", "ingredientes": [{"item": "Yogurt Griego", "cantidad": 300, "unidad": "g", "pasillo": "🥛 Lácteos"}, {"item": "Frutos Rojos", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Almendras", "cantidad": 15, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Revuelto Pavita Tomate", "descripcion": "Rápido y proteico", "macros": {"cal": 450, "prot": 40, "carb": 20, "fat": 22}, "instrucciones": "Saltear jamón con huevos y tomate cherry.", "ingredientes": [{"item": "Huevos", "cantidad": 3, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Jamón Pavita", "cantidad": 100, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Tomate Cherry", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Quesadilla Fit", "descripcion": "Versión saludable", "macros": {"cal": 500, "prot": 35, "carb": 50, "fat": 18}, "instrucciones": "Tortilla integral con pollo y queso. A la plancha.", "ingredientes": [{"item": "Tortilla Integral", "cantidad": 2, "unidad": "und", "pasillo": "🍞 Panadería"}, {"item": "Pollo Desmechado", "cantidad": 100, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Queso Light", "cantidad": 60, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Crepe Proteico", "descripcion": "Alta proteína", "macros": {"cal": 460, "prot": 38, "carb": 45, "fat": 15}, "instrucciones": "Crepe de claras relleno de requesón y fresas.", "ingredientes": [{"item": "Claras Huevo", "cantidad": 6, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Avena", "cantidad": 40, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Requesón", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Fresas", "cantidad": 50, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Pan Árabe Atún", "descripcion": "Mediterráneo", "macros": {"cal": 480, "prot": 35, "carb": 50, "fat": 15}, "instrucciones": "Pan árabe con atún, pepino y yogurt.", "ingredientes": [{"item": "Pan Árabe", "cantidad": 2, "unidad": "und", "pasillo": "🍞 Panadería"}, {"item": "Atún", "cantidad": 120, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Pepino", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Yogurt", "cantidad": 50, "unidad": "g", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Tortilla Francesa Jamón", "descripcion": "Clásico ligero", "macros": {"cal": 440, "prot": 35, "carb": 12, "fat": 28}, "instrucciones": "Tortilla con jamón de pavo y queso.", "ingredientes": [{"item": "Huevos", "cantidad": 3, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Jamón Pavita", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Queso", "cantidad": 30, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Ensalada Pollo Power", "descripcion": "Fresco y completo", "macros": {"cal": 480, "prot": 45, "carb": 30, "fat": 20}, "instrucciones": "Mix verde con pollo grillado, palta y tostadas.", "ingredientes": [{"item": "Pollo", "cantidad": 150, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Lechuga Mix", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Palta", "cantidad": 40, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Pan Tostado", "cantidad": 2, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}]},
        {"nombre": "Avena Salada Huevo", "descripcion": "Original y nutritivo", "macros": {"cal": 450, "prot": 30, "carb": 55, "fat": 15}, "instrucciones": "Avena cocida con huevo poché y espinaca.", "ingredientes": [{"item": "Avena", "cantidad": 70, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Huevo", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Espinaca", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Muffin Huevo Jamón", "descripcion": "Porcionado y práctico", "macros": {"cal": 420, "prot": 32, "carb": 30, "fat": 20}, "instrucciones": "Muffins de huevo con jamón en moldes.", "ingredientes": [{"item": "Huevos", "cantidad": 4, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Jamón Pavita", "cantidad": 80, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Vegetales", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Crema Brócoli Pollo", "descripcion": "Reconfortante", "macros": {"cal": 460, "prot": 40, "carb": 35, "fat": 18}, "instrucciones": "Crema de brócoli con trozos de pollo.", "ingredientes": [{"item": "Brócoli", "cantidad": 300, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Pollo", "cantidad": 150, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Leche Light", "cantidad": 100, "unidad": "ml", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Tostada Requesón Miel", "descripcion": "Dulce saludable", "macros": {"cal": 440, "prot": 28, "carb": 50, "fat": 15}, "instrucciones": "Pan integral con requesón, miel y nueces.", "ingredientes": [{"item": "Pan Integral", "cantidad": 2, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}, {"item": "Requesón", "cantidad": 100, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Miel", "cantidad": 15, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Nueces", "cantidad": 15, "unidad": "g", "pasillo": "🥫 Abarrotes"}]},
        {"nombre": "Batido Verde Proteico", "descripcion": "Líquido y nutritivo", "macros": {"cal": 420, "prot": 35, "carb": 50, "fat": 10}, "instrucciones": "Licuar espinaca, plátano, proteína y leche.", "ingredientes": [{"item": "Espinaca", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Plátano", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Scoop Proteína", "cantidad": 1, "unidad": "und", "pasillo": "💊 Suplementos"}, {"item": "Leche Light", "cantidad": 200, "unidad": "ml", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Pizza Tortilla Fitness", "descripcion": "Crujiente y proteica", "macros": {"cal": 500, "prot": 38, "carb": 50, "fat": 18}, "instrucciones": "Tortilla integral como base con salsa, pollo y queso.", "ingredientes": [{"item": "Tortilla Integral", "cantidad": 2, "unidad": "und", "pasillo": "🍞 Panadería"}, {"item": "Salsa Tomate", "cantidad": 50, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Pollo", "cantidad": 100, "unidad": "g", "pasillo": "🥩 Carnicería"}, {"item": "Queso Light", "cantidad": 50, "unidad": "g", "pasillo": "🧀 Charcutería"}]},
        {"nombre": "Sándwich Huevo Palta", "descripcion": "Energía nocturna", "macros": {"cal": 480, "prot": 28, "carb": 45, "fat": 25}, "instrucciones": "Pan integral con huevo duro y palta.", "ingredientes": [{"item": "Pan Integral", "cantidad": 2, "unidad": "rebanadas", "pasillo": "🍞 Panadería"}, {"item": "Huevo Duro", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Palta", "cantidad": 50, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Bowl Quinua Vegetales", "descripcion": "Veggie proteico", "macros": {"cal": 450, "prot": 25, "carb": 60, "fat": 15}, "instrucciones": "Quinua con vegetales salteados y huevo.", "ingredientes": [{"item": "Quinua Cocida", "cantidad": 150, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Vegetales Mix", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Huevo", "cantidad": 1, "unidad": "und", "pasillo": "🥛 Lácteos"}]},
        {"nombre": "Rollitos Lechuga Atún", "descripcion": "Cero carbos pesados", "macros": {"cal": 400, "prot": 38, "carb": 15, "fat": 20}, "instrucciones": "Hojas de lechuga rellenas de atún y palta.", "ingredientes": [{"item": "Lechuga", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Atún", "cantidad": 150, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Palta", "cantidad": 40, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Tortilla Atún Cebolla", "descripcion": "Española fit", "macros": {"cal": 460, "prot": 35, "carb": 25, "fat": 25}, "instrucciones": "Tortilla gruesa con atún y cebolla caramelizada.", "ingredientes": [{"item": "Huevos", "cantidad": 3, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Atún", "cantidad": 100, "unidad": "g", "pasillo": "🥫 Abarrotes"}, {"item": "Cebolla", "cantidad": 80, "unidad": "g", "pasillo": "🥦 Verdulería"}]},
        {"nombre": "Huevos Benedictinos Fit", "descripcion": "Versión saludable", "macros": {"cal": 490, "prot": 32, "carb": 40, "fat": 25}, "instrucciones": "Muffin inglés con huevo poché y salsa de yogurt.", "ingredientes": [{"item": "Muffin Inglés", "cantidad": 2, "unidad": "und", "pasillo": "🍞 Panadería"}, {"item": "Huevo", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}, {"item": "Jamón Pavita", "cantidad": 50, "unidad": "g", "pasillo": "🧀 Charcutería"}, {"item": "Yogurt", "cantidad": 50, "unidad": "g", "pasillo": "🥛 Lácteos"}]}
    ],

    # ==========================================================
    # 25 MERIENDAS (Sin cambios)
    # ==========================================================
    "Meriendas": [
         {"nombre": "Batido Post-Entreno", "descripcion": "Recuperación.", "macros": {"cal": 250, "prot": 25, "carb": 30, "fat": 2}, "ingredientes": [{"item": "Scoop Proteína", "cantidad": 1, "unidad": "und", "pasillo": "💊 Suplementos"}], "instrucciones": "Licuar."},
         {"nombre": "Yogurt y Almendras", "descripcion": "Grasas buenas.", "macros": {"cal": 280, "prot": 15, "carb": 10, "fat": 18}, "ingredientes": [{"item": "Yogurt", "cantidad": 150, "unidad": "g", "pasillo": "🥛 Lácteos"}, {"item": "Almendras", "cantidad": 15, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Mezclar."},
         {"nombre": "Huevo Duro x2", "descripcion": "Proteína pura.", "macros": {"cal": 140, "prot": 12, "carb": 1, "fat": 10}, "ingredientes": [{"item": "Huevos", "cantidad": 2, "unidad": "und", "pasillo": "🥛 Lácteos"}], "instrucciones": "Hervir."},
         {"nombre": "Plátano", "descripcion": "Potasio.", "macros": {"cal": 100, "prot": 1, "carb": 25, "fat": 0}, "ingredientes": [{"item": "Plátano", "cantidad": 1, "unidad": "und", "pasillo": "🥦 Verdulería"}], "instrucciones": "Comer."},
         {"nombre": "Manzana", "descripcion": "Fibra.", "macros": {"cal": 80, "prot": 0, "carb": 20, "fat": 0}, "ingredientes": [{"item": "Manzana", "cantidad": 1, "unidad": "und", "pasillo": "🥦 Verdulería"}], "instrucciones": "Lavar."},
         {"nombre": "Tostada Maní", "descripcion": "Energía.", "macros": {"cal": 250, "prot": 8, "carb": 25, "fat": 15}, "ingredientes": [{"item": "Pan", "cantidad": 1, "unidad": "rebanada", "pasillo": "🍞 Panadería"}, {"item": "Maní", "cantidad": 15, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Untar."},
         {"nombre": "Gelatina", "descripcion": "Ansiedad.", "macros": {"cal": 20, "prot": 2, "carb": 0, "fat": 0}, "ingredientes": [{"item": "Gelatina", "cantidad": 1, "unidad": "taza", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Comer."},
         {"nombre": "Nueces", "descripcion": "Omega 3.", "macros": {"cal": 180, "prot": 4, "carb": 4, "fat": 18}, "ingredientes": [{"item": "Nueces", "cantidad": 30, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Comer."},
         {"nombre": "Queso Cubos", "descripcion": "Caseína.", "macros": {"cal": 150, "prot": 12, "carb": 2, "fat": 10}, "ingredientes": [{"item": "Queso", "cantidad": 50, "unidad": "g", "pasillo": "🧀 Charcutería"}], "instrucciones": "Picado."},
         {"nombre": "Rollitos Pavo", "descripcion": "Ligero.", "macros": {"cal": 100, "prot": 20, "carb": 2, "fat": 2}, "ingredientes": [{"item": "Jamón Pavo", "cantidad": 100, "unidad": "g", "pasillo": "🧀 Charcutería"}], "instrucciones": "Enrollar."},
         {"nombre": "Atún Lata", "descripcion": "Emergencia.", "macros": {"cal": 120, "prot": 28, "carb": 0, "fat": 1}, "ingredientes": [{"item": "Atún", "cantidad": 120, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Comer."},
         {"nombre": "Chocolate Negro", "descripcion": "Antioxidante.", "macros": {"cal": 150, "prot": 2, "carb": 12, "fat": 10}, "ingredientes": [{"item": "Chocolate", "cantidad": 20, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "2 cuadritos."},
         {"nombre": "Galletas Arroz", "descripcion": "Crujiente.", "macros": {"cal": 100, "prot": 2, "carb": 22, "fat": 1}, "ingredientes": [{"item": "Galletas", "cantidad": 3, "unidad": "und", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Comer."},
         {"nombre": "Zanahoria Hummus", "descripcion": "Dip.", "macros": {"cal": 200, "prot": 6, "carb": 25, "fat": 10}, "ingredientes": [{"item": "Zanahoria", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}, {"item": "Hummus", "cantidad": 50, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Untar."},
         {"nombre": "Aceitunas", "descripcion": "Grasas.", "macros": {"cal": 100, "prot": 0, "carb": 2, "fat": 10}, "ingredientes": [{"item": "Aceitunas", "cantidad": 10, "unidad": "und", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Comer."},
         {"nombre": "Café Leche", "descripcion": "Cafeína.", "macros": {"cal": 80, "prot": 8, "carb": 10, "fat": 0}, "ingredientes": [{"item": "Leche", "cantidad": 100, "unidad": "ml", "pasillo": "🥛 Lácteos"}], "instrucciones": "Beber."},
         {"nombre": "Barra Proteica", "descripcion": "Procesado.", "macros": {"cal": 200, "prot": 20, "carb": 20, "fat": 8}, "ingredientes": [{"item": "Barra", "cantidad": 1, "unidad": "und", "pasillo": "💊 Suplementos"}], "instrucciones": "Comer."},
         {"nombre": "Palta Sola", "descripcion": "Saciante.", "macros": {"cal": 160, "prot": 2, "carb": 8, "fat": 15}, "ingredientes": [{"item": "Palta", "cantidad": 100, "unidad": "g", "pasillo": "🥦 Verdulería"}], "instrucciones": "Comer."},
         {"nombre": "Tomate Cherry", "descripcion": "Fresco.", "macros": {"cal": 50, "prot": 2, "carb": 10, "fat": 0}, "ingredientes": [{"item": "Tomate", "cantidad": 150, "unidad": "g", "pasillo": "🥦 Verdulería"}], "instrucciones": "Lavar."},
         {"nombre": "Sandía", "descripcion": "Agua.", "macros": {"cal": 60, "prot": 1, "carb": 15, "fat": 0}, "ingredientes": [{"item": "Sandía", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}], "instrucciones": "Picada."},
         {"nombre": "Piña", "descripcion": "Digestión.", "macros": {"cal": 80, "prot": 1, "carb": 20, "fat": 0}, "ingredientes": [{"item": "Piña", "cantidad": 150, "unidad": "g", "pasillo": "🥦 Verdulería"}], "instrucciones": "Rodajas."},
         {"nombre": "Avena Instant", "descripcion": "Carbo.", "macros": {"cal": 150, "prot": 5, "carb": 27, "fat": 3}, "ingredientes": [{"item": "Avena", "cantidad": 40, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Agua caliente."},
         {"nombre": "Chocolatada Light", "descripcion": "Antojo.", "macros": {"cal": 150, "prot": 8, "carb": 20, "fat": 2}, "ingredientes": [{"item": "Leche", "cantidad": 200, "unidad": "ml", "pasillo": "🥛 Lácteos"}, {"item": "Cacao", "cantidad": 5, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Mezclar."},
         {"nombre": "Pepino", "descripcion": "Volumen.", "macros": {"cal": 30, "prot": 1, "carb": 5, "fat": 0}, "ingredientes": [{"item": "Pepino", "cantidad": 200, "unidad": "g", "pasillo": "🥦 Verdulería"}], "instrucciones": "Rodajas."},
         {"nombre": "Cancha", "descripcion": "Salado.", "macros": {"cal": 150, "prot": 3, "carb": 30, "fat": 2}, "ingredientes": [{"item": "Cancha", "cantidad": 30, "unidad": "g", "pasillo": "🥫 Abarrotes"}], "instrucciones": "Tostar."}
    ]
}
